[package]
name = "advent-of-code-2019"
version = "0.1.0"
authors = ["boxdot <d@zerovolt.org>"]
edition = "2018"

[dependencies]
itertools = "0.8.2"
regex = "1.3.1"
permutohedron = "0.2.4"
bytecount = "0.6.0"
num-integer = "0.1.41"
